language: c
dist: bionic

notifications:
  email: false

cache:
  directories:
    - dependencies

before_install:
  sudo apt-get install -y libsqlite3-dev gcc-4.8 gettext python python3 python3-mako net-tools zlib1g-dev libsodium-dev

script:
  .travis/build.sh

